apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: caddy-ingress
spec:
    ingressClassName: nginx
    rules:
    - host: argocd-dev.damtest.br
      http:
        paths:
        - path: /caddy
          pathType: Prefix
          backend:
            service:
              name: caddy-service
              port:
                name: http