apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgCXkGK/HRWip3GzGkafJ0pH6sy0jy1ZrDMYAugJShlBNSoa1EhOyR3PBJv/oqZ+YulfAk/mm1N/ztXBMn0UYELwffN5pghhpLtRwSFm2mq9pU0WuFbNsPjw0X6yzbLyNnIIpHNoO4pYE6azYGfhdF4nWcLJPPiiWm09tBaWJdrq85Cq0Q7S1f6I1BQcCsxs1neZGHKm4yS9VfMQ86dk7aH4DH5dY8+WkxiaKkwWWLyo6ok8lw/c7jZV5+omOz8QGdpBDg77rOOz3nE0jaMAm/ltRZDbQ+ogbXC+okeTSje3rxCKe5uh2IQaR1tbrzyeUDykxkCEFgbIltrW3yfHIpx8Fy6ykR06xOsCa0CA4KBFVhdYnLteb95weCF8qStmnARq/p5o3p/UjM+u7/894aAocbWpRWffQTWQGp4bAd4dSWhZ+D9GoHN+0nn0rpJSLrHHmOqp2n4l9GgM+fqSd+knIS4dUFb9CwhF8m78RLwC/ibTPH8xcLD0hmzQLdgxYI4bV+KBg1+Q/4YwZxM2AEWTC9jiw4bL6TwLtDIUrjI2zfYsWtFoAeBU43HrZaMHicQyF3h1/27ZWQTQGfr+59BPd/s1k8kzp+RcFbNu4lVv0hweTG6XT2ctyV0I2TA6F3e9OHJaSU+XeuncOILdDiJBAI5j6fERYxn8lZZD0rcpwr+G0Wzml1Yz4VrWVL/BdTgxA+T5e8wrmpvs7NMGkVBJ6vq3JFPxkgzcJ558XF+MpWYDE6RVcTU=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque