---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgCW7KCfPOIOwg4rm63Jy0vv+Mea7BRJbG6+XirsW9P+HzR3KyLIf/GuqxpofuZndfrCNt+nDG1yrJaubDot85J4HT6+RKvaK7FqU2prmzuh9rW6MhcEQ0QFYyGF7S8NGZXiTNDtT+vmAFATb2xAM3nh0PL+xRRKihWhIlEoLnrYVo9iNFo4gHegt5qDld0DtCE1gVp/Yi8Pxpme045R/1XK4k9V8OL7boG5UK+xelT+Rc0RLHCHXf+njBzig0YAvchEIqhOVEyPUqvJ68gG5YcdkPV5wyvS3hIaoTe6DvtZn1/UfPGKROIeztoDvPj5deAWJN37k/F72InsM3jq6zuJypLVOmSjSed9GJbpxkm/am6dPya+sWHzAUVP1jTfUjF+tYBRHxZacpSviDqrKkt4qvFcAFwSPZxlcKcK1tUW/KfM2BV+N8EWagcYieEaOiI2ehJ+Hb85DJC8yBjx3RBgmy5TaWBZnrrHeJ6gYLZdrPWcQiNGVLpXtodwDS0txYbgQ8ruHekCJ6E4ZncV0CY0Syn7KCcz1LZLaPceh+7WmHT5kCA2CFnXj77vhzyIMmhTh1CdPy4zn9dPeXg38iTpGtaKndpXG6qXyeIFQxnYoEi8GyiHyekpzwZIbZ4dV7Chj4/g0xymDW5Nc6uMX5oWP3wW1AkkPHJmzG9hj6WL4lx+Y4c75yLDr4WD457XzrxVAMTITjvol2N6ur1NCY/lJRFOSMcd4LG0U6Hi53ekQZPhZX4UAJQ=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
