apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations: 
    argocd.argoproj.io/sync-options: Replace=true
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.2.2
    chart: kube-prometheus-stack
  destination:
      server: https://kubernetes.default.svc
      namespace: default
  syncPolicy:
      automated:
        selfHeal: true
        prune: true