apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/spring
    repoURL: git@github.com:damiao-santos/springbot.git
    targetRevision: main
    helm:
      releaseName: spring
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: springboot
  syncPolicy:
    automated:
      selfHeal: true
      prune: true